[phases.setup]
	nixPkgs = ['nodejs_20', 'python3']

[phases.build]
cmds = ['cd frontend && npm install && npm run build']

[start]
cmd = 'gunicorn --bind 0.0.0.0:$PORT wsgi:app'
env = { PORT = '$PORT' }